Repository osism/container-image-ceph-ansible, pull requests merged in 2021-05, with the labels that each got.

#115 Only remove 99-netbox.yml if /ansible/inventory is writable
  files/scripts/run.sh
Labels: Type: Bugfix

#117 Rename repository to container-image-ceph-ansible
  .github/workflows/build-docker-image.yml
  .github/workflows/check-docker-syntax.yml
  Containerfile
  Dockerfile
  README.md
  scripts/build.sh
Labels: Type: Feature

#118 ceph-facts playbook should apply the ceph-facts role as well
  files/playbooks/luminous/ceph-facts.yml
  files/playbooks/master/ceph-facts.yml
  files/playbooks/nautilus/ceph-facts.yml
  files/playbooks/octopus/ceph-facts.yml
  files/playbooks/pacific/ceph-facts.yml
Labels: Type: Feature

#119 Revert "Add sudo to be able to run local actions"
  Containerfile
  files/dragon_sudoers
Labels: Type: Feature

#120 Use the ansible-defaults repository
  Containerfile
  files/defaults.yml
  files/images-luminous.yml
  files/images-master.yml
  files/images-nautilus.yml
  files/images-octopus.yml
  files/images-pacific.yml
  files/images.yml
Labels: Type: Feature

#121 Allow manual workflow triggering
  .github/workflows/build-docker-image.yml
Labels: Type: CI
